### ISSUE TITLE
Download of data from Fidelity is not possible anymore

### ISSUE THREAD

**Issue by RSchallock** [lumaxis/fidelity-netbenefits#12]
Trying to download the data from the Fidelity account with netbenefits.lua (version 0.11) does not work anymore since a while.
The software gives the following error message:

"Fidelity is having technical issues or is throttling your logins. Please try again later"

Login credentials have been checked several times and are correct.

Is there a new version of the plug-in available that copes with the problem?

**Comment by jbeckerwsi** [comment]
looks to be the same issue as #10

**Comment by lumaxis** [comment]
Indeed, closing in favor of #10.
